baseurl:
exclude: ['README.md']
permalink: pretty

collections:
  people:
    output: true
    output_ext: .html
    permalink: /people/:path/

  projects:
    output: true4
    output_ext: .html    
    permalink: /projects/:path/