baseurl: /TreeBranchWebsite
exclude: ['README.md']
permalink: pretty

collections:
  games:
    output: true
    permalink: /games/:path/

    people:
      output: true
      permalink: /people/:path/